### ISSUE TITLE
Design for showing average payments on mvp [$50]

### ISSUE THREAD

**Issue by danirabbit** [elementary/mockups#4]
A design for [mvp issue #421](https://github.com/elementary/mvp/issues/421)

Concept: What about a popover that shows when you click the "Custom" field? Would be relatively unobtrusive and give us a fresh space to show info.
## 

[Bounty on Bountysource](https://www.bountysource.com/issues/29536708-design-for-showing-average-payments-on-mvp)

**Comment by harveycabaguio** [comment]
Fixed with commit 775bfd147222611182dbcc02fe0e5e2be532fa28
